### ISSUE TITLE
Getting an error when running in Docker Desktop.

### ISSUE THREAD

**Issue by Bravry** [Choff3/letterboxd-sync#9]
Getting an error when running in Docker Desktop. I don't have either of the Radarr variable set for the container but do have all Plex variables set. What should I do?

2024-02-24 03:25:20 Traceback (most recent call last):
2024-02-24 03:25:20   File "/usr/src/app/./main.py", line 32, in <module>
2024-02-24 03:25:20     main()
2024-02-24 03:25:20   File "/usr/src/app/./main.py", line 18, in main
2024-02-24 03:25:20     radarr_films = plex_watchlist_add(films,plex_host,plex_token)
2024-02-24 03:25:20                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 03:25:20   File "/usr/src/app/plex_watchlist.py", line 13, in plex_watchlist_add
2024-02-24 03:25:20     for film in letterboxdFilms:
2024-02-24 03:25:20 TypeError: 'NoneType' object is not iterable

**Comment by Choff3** [comment]
Paste your run command
